@startuml
start

:call Minimax(node, depth, isMaximizing);

if (terminal node OR depth == 0?) then (yes)
  :evaluate node;
  :return evaluation;
  stop
else (no)
    if (isMaximizing?) then (yes)
      :bestValue = -infinity;
      repeat
        :generate child node;
        :value = Minimax(child, depth-1, !isMaximizing);
        :bestValue = max(bestValue, value);
      repeat while (More children?)
    else (no)
      :bestValue = +infinity;
      repeat
        :generate child node;
        :value = Minimax(child, depth-1, !isMaximizing);
        :bestValue = min(bestValue, value);
      repeat while (More children?)
    endif
endif

:return bestValue;
stop

@enduml