@startuml
skinparam dpi 300

' Force top-down layout
top to bottom direction

package "Stufe 0 (max)" {
    node "_" as L0
}

package "Stufe 1 (min)" {
    node "_" as L1L
    node "_" as L1R
}

package "Stufe 2 (max)" {
    node "2" as L2LL
    node "5" as L2LR
    node "4" as L2RL
    node "12" as L2RM
    node "8" as L2RR
}

' Connections
L0 --> L1L
L0 --> L1R
L1L --> L2LL
L1L --> L2LR
L1R --> L2RL
L1R --> L2RM
L1R --> L2RR

@enduml