@startchart

title
FEN: 8/5ppk/4p1p1/3pq3/3Q4/1B2r2P/P5P1/3R3K b - - 8 42
end title

h-axis [Depth1,Depth2,Depth3,Depth4]
v-axis "Calculation time [s]" 0 --> 8 spacing 1 grid

bar "MiniMaxSequential (Simple material evaluation)"[ 1.0E-5, 0.006, 0.197,6.333 ] #1F77B4
bar "MiniMaxSequential (Mate aware material evaluation)"[ 1.0E-5,0.008,0.241,7.708 ] #FF7F0E
bar "MiniMaxParallel (Simple material evaluation)"[ 1.0E-5,0.001,0.019,0.811 ] #2CA02C
bar "MiniMaxParallel (Mate aware material evaluation)"[ 1.0E-5,0.001,0.025,0.979 ] #D62728


legend right
@endchart
