@startuml

class ch.hslu.cas.msed.blobfish.base.FenUtil {
	{method}  {static} +getFenPositionBlocks ( paramString1 : String ) : [Ljava.lang.String;
	{method}  {static} +isFenStringValid ( paramString1 : String ) : void
}


class ch.hslu.cas.msed.blobfish.base.Piece {
	{method} +color () : ch.hslu.cas.msed.blobfish.base.PlayerColor
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +fen () : Character
	{method} +hashCode () : int
	{method} +materialPoints () : int
	{method} +toString () : String
	{method} +type () : ch.hslu.cas.msed.blobfish.base.PieceType
}


enum ch.hslu.cas.msed.blobfish.base.PieceType {
	{field} +BISHOP
	{field} +KING
	{field} +KNIGHT
	{field} +PAWN
	{field} +QUEEN
	{field} +ROOK
}


enum ch.hslu.cas.msed.blobfish.base.PlayerColor {
	{field} +BLACK
	{field} +WHITE
}




ch.hslu.cas.msed.blobfish.base.Piece *--  ch.hslu.cas.msed.blobfish.base.PieceType : type
ch.hslu.cas.msed.blobfish.base.Piece *--  ch.hslu.cas.msed.blobfish.base.PlayerColor : color


@enduml