@startuml

abstract class ch.hslu.cas.msed.blobfish.player.AbstractPlayer {
	{field} -playerColor : ch.hslu.cas.msed.blobfish.base.PlayerColor
	{method}  {abstract} +getNextMove ( paramChessBoard1 : ch.hslu.cas.msed.blobfish.board.ChessBoard ) : String
}


class ch.hslu.cas.msed.blobfish.player.HumanPlayer {
	{field} -reader : ch.hslu.cas.msed.blobfish.game.InputReader
	{method} +getNextMove ( paramChessBoard1 : ch.hslu.cas.msed.blobfish.board.ChessBoard ) : String
}


abstract class ch.hslu.cas.msed.blobfish.player.bot.BotPlayer {
}


abstract class ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxAlgo {
	{field} -calculationDepth : int
	{field} -evalStrategy : ch.hslu.cas.msed.blobfish.eval.EvalStrategy
	{field} -ownPlayerColor : ch.hslu.cas.msed.blobfish.base.PlayerColor
	{method}  {abstract} +getBestNextMove ( paramChessBoard1 : ch.hslu.cas.msed.blobfish.board.ChessBoard ) : String
}


class ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxBotPlayer {
	{method} +getNextMove ( paramChessBoard1 : ch.hslu.cas.msed.blobfish.board.ChessBoard ) : String
}


class ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxSequential {
	{method} -calcBestPath ( paramChessBoard1 : ch.hslu.cas.msed.blobfish.board.ChessBoard , paramint2 : int , paramPlayerColor3 : ch.hslu.cas.msed.blobfish.base.PlayerColor , paramLinkedList4 : java.util.LinkedList ) : ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxSequential$BottomNode
	{method} -copyAndAddToHistory ( paramLinkedList1 : java.util.LinkedList , paramMove2 : com.github.bhlangonijr.chesslib.move.Move ) : java.util.LinkedList
	{method} +getBestNextMove ( paramChessBoard1 : ch.hslu.cas.msed.blobfish.board.ChessBoard ) : String
	{method}  {static} -getSanOfMove ( paramMove1 : com.github.bhlangonijr.chesslib.move.Move ) : String
}


class ch.hslu.cas.msed.blobfish.player.exceptions.InvalidMoveException {
	{field} -originalMove : String
}




ch.hslu.cas.msed.blobfish.player.HumanPlayer --|>  ch.hslu.cas.msed.blobfish.player.AbstractPlayer
ch.hslu.cas.msed.blobfish.player.bot.BotPlayer --|>  ch.hslu.cas.msed.blobfish.player.AbstractPlayer
ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxBotPlayer *--  ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxAlgo : miniMaxAlgo
ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxBotPlayer --|>  ch.hslu.cas.msed.blobfish.player.bot.BotPlayer
ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxSequential --|>  ch.hslu.cas.msed.blobfish.player.bot.minimax.MiniMaxAlgo


@enduml