@startchart

title
FEN: 8/5ppk/4p1p1/3pq3/3Q4/1B2r2P/P5P1/3R3K b - - 8 42
end title

h-axis [Depth1,Depth2,Depth3,Depth4]
v-axis "Performance [ms]" 0 --> 800 spacing 100

bar "MiniMaxSequential (Simple material evaluation)"[ 1.0E-5,6,197,6333 ] #1F77B4
bar "MiniMaxSequential (Mate aware material evaluation)"[ 1.0E-5,8,241,7708 ] #FF7F0E
bar "MiniMaxParallel (Simple material evaluation)"[ 1.0E-5,1,19,811 ] #2CA02C
bar "MiniMaxParallel (Mate aware material evaluation)"[ 1.0E-5,1,25,979 ] #D62728


legend right
@endchart
