@startchart

title
FEN: r5k1/7p/1p1Qp1p1/p1np1r2/1q3P1P/1P6/2P3P1/RB3RK1 w - - 3 26
end title

h-axis [Depth1,Depth2,Depth3,Depth4]
v-axis "Calculation time [s]" 0 --> 14 spacing 1 grid

bar "MiniMaxSequential (Simple material evaluation)"[ 1.0E-5,0.009,0.301,10.936 ] #1F77B4
bar "MiniMaxSequential (Mate aware material evaluation)"[ 1.0E-5,0.011,0.365,13.225 ] #FF7F0E
bar "MiniMaxParallel (Simple material evaluation)"[ 1.0E-5,0.001,0.029,1.375 ] #2CA02C
bar "MiniMaxParallel (Mate aware material evaluation)"[ 1.0E-5,0.001,0.036,1.610 ] #D62728


legend right
@endchart
