@startchart

title
FEN: 5r1k/1pqnbr1P/p2p1pQp/2p5/3PP2P/1PN5/1PP3R1/R5K1 w - - 0 24
end title

h-axis [Depth1,Depth2,Depth3,Depth4]
v-axis "Calculation time [s]" 0 --> 12 spacing 1 grid

bar "MiniMaxSequential (Simple material evaluation)"[ 1.0E-5,0.009,0.391,10.046 ] #1F77B4
bar "MiniMaxSequential (Mate aware material evaluation)"[ 1.0E-5,0.011,0.474,12.087 ] #FF7F0E
bar "MiniMaxParallel (Simple material evaluation)"[ 1.0E-5,0.001,0.038,1.222 ] #2CA02C
bar "MiniMaxParallel (Mate aware material evaluation)"[ 1.0E-5,0.001,0.048,1.435 ] #D62728


legend right
@endchart
