@startchart

title
Calculation time with depth 4
end title

h-axis [V1, V2, V3, V4]

v-axis "Calculation time [s]" 0 --> 25 spacing 2 grid

bar "Complex Position with may Options" [ 26.148, 31.692, 3.185, 3.783 ] #1F77B4
bar "Endgame Deflection" [ 6.333,  7.708, 0.811, 0.979 ] #FF7F0E
bar "Midgame Deflection" [ 13.900, 16.919, 1.828, 2.121 ] #2CA02C
bar "Midgame Discovery M2" [ 6.090, 7.402, 0.787, 0.899 ] #D62728
bar "Midgame Discovery Short" [ 10.936, 13.225, 1.375, 1.610 ] #9467BD
bar "Midgame en passant" [ 12.078, 14.507, 1.480, 1.716 ] #8C564B
bar "Midgame fork" [ 35.243, 42.137, 3.994, 4.758 ] #E377C2
bar "Midgame promotion" [ 10.046, 12.087, 1.222, 1.435 ] #7F7F7F

legend
ComplexPositionWithManyOptions = 1r4r1/5p1k/p2p1q1p/2b1nPQ1/p7/6RP/B1R2PPK/2B5 b - - 0 1
EndGame Deflection = 8/5ppk/4p1p1/3pq3/3Q4/1B2r2P/P5P1/3R3K b - - 8 42
MidGame Deflection = 5rk1/5q1p/p2PR1p1/4p1b1/1pP5/1P1Q4/P5PP/1K2R3 b - - 0 31
Midgame Discovery M2 = Q7/p1pk3p/2p2qp1/3p1b2/8/1PN1P3/P1PP2PP/R4KNR b - - 4 15
Midgame Discovery Short = r5k1/7p/1p1Qp1p1/p1np1r2/1q3P1P/1P6/2P3P1/RB3RK1 w - - 3 26
Midgame en passant = rn1q1r1k/pbpp1p1p/1p2p3/4P3/3P2Qp/P2B4/1PP2PPP/R4RK1 w - - 0 17
Midgame fork = r3k2r/pNp1ppbp/2nq2pn/7P/2B3b1/3P1N2/PPP2PP1/R1BQK2R b KQkq - 0 11
Midgame promotion = 5r1k/1pqnbr1P/p2p1pQp/2p5/3PP2P/1PN5/1PP3R1/R5K1 w - - 0 24

V1 = MiniMaxSequential (Simple material evaluation),
V2 = MiniMaxSequential (Mate aware material evaluation),
V3 = MiniMaxParallel (Simple material evaluation),
V4 = MiniMaxParallel (Mate aware material evaluation)
end legend

legend right

@endchart
