@startuml
!include <C4/C4_Component>

title Component Diagramm

Person(human, "Schachspieler")

Container_Boundary(cli, "Blobfish") {
    Component(base, "base", "Java Package", "Grundlegende Datenstrukturen wie ChessBoard, Piece, sowie Util Klassen")
    Component(eval, "eval", "Java Package", "Heuristiken um Schachpositionen zu beurteilen")
    Component(game, "game", "Java Package", "Spielsteuerung, UI und Terminal-Interaktion")
    Component(minimax, "minimax", "Java Package", "MiniMax-Algorithmen")
    Component(player, "player", "Java Package", "Spieler Abstraktion")
}

System_Ext(chesslib, "chesslib", "Java-Bibliothek für Zuggenerierung, Zugvalidierung und PGN/FEN generierung")
System_Ext(jline, "jline", "Java-Bibliothek für Terminal-Input handling")

Rel(base, chesslib, "verwendet")

Rel(eval, base, "verwendet")

Rel(game, base, "verwendet")
Rel(game, eval, "verwendet")
Rel(game, player, "verwendet")
Rel(game, minimax, "verwendet")
Rel(game, jline, "verwendet")

Rel(minimax, base, "verwendet")
Rel(minimax, eval, "verwendet")
Rel(minimax, player, "verwendet")

Rel(player, base, "verwendet")
Rel(player, game, "verwendet")

Rel(human, game, "Interagiert via Terminal")


@enduml
