@startuml
!include <C4/C4_Container>

title Container Diagramm

Person(player, "Schachspieler", "Spielt Schach über das Terminal.")

System_Boundary(blobfish, "Blobfish") {
    Container(cli, "Applikation", "Java 25", "Schachcomputer mit Algorithmen, Bewertungsfunktionen und Terminal-UI.")
}

System_Ext(chesslib, "chesslib", "Java-Bibliothek für legale Zuggenerierung, Zugvalidierung und PGN/FEN Generierung")
System_Ext(jline, "jline", "Java-Bibliothek für Terminal-Input handeling")


Rel(player, jline, "Interagiert via", "CLI / Terminal")
Rel(cli, chesslib, "Verwendet für die Zuggenerierung und Zugvalidierung")
Rel(cli, jline, "Interagiert via")



@enduml
