@startchart

title
FEN: Q7/p1pk3p/2p2qp1/3p1b2/8/1PN1P3/P1PP2PP/R4KNR b - - 4 15
end title

h-axis [Depth1,Depth2,Depth3,Depth4]
v-axis "Performance [ms]" 0 --> 800 spacing 100

bar "MiniMaxSequential (Simple material evaluation)"[ 1.0E-5,7,192,6090 ] #1F77B4
bar "MiniMaxSequential (Mate aware material evaluation)"[ 1.0E-5,8,233,7402 ] #FF7F0E
bar "MiniMaxParallel (Simple material evaluation)"[ 1.0E-5,1,19,787 ] #2CA02C
bar "MiniMaxParallel (Mate aware material evaluation)"[ 1.0E-5,1,24,899 ] #D62728


legend right
@endchart
