@startchart

title
FEN: Q7/p1pk3p/2p2qp1/3p1b2/8/1PN1P3/P1PP2PP/R4KNR b - - 4 15
end title

h-axis [Depth1,Depth2,Depth3,Depth4]
v-axis "Calculation time [s]" 0 --> 8 spacing 1 grid

bar "MiniMaxSequential (Simple material evaluation)"[ 1.0E-5,0.007,0.192,6.090 ] #1F77B4
bar "MiniMaxSequential (Mate aware material evaluation)"[ 1.0E-5,0.008,0.233,7.402 ] #FF7F0E
bar "MiniMaxParallel (Simple material evaluation)"[ 1.0E-5,0.001,0.019,0.787 ] #2CA02C
bar "MiniMaxParallel (Mate aware material evaluation)"[ 1.0E-5,0.001,0.024,0.899 ] #D62728


legend right
@endchart
